### ISSUE TITLE
KCD to concept id mapping in [Closed fracture of neck of femur]

### ISSUE THREAD

**Issue by HojunPark** [OHDSI/ETL---Korean-NSC#3]
The KCD codes 'S720#' are mapped to concept id 433856(Fracture of neck of femur).

S7200, S72020, S72030, S72040, S72050, S72060, S72080, S72090 (finished with 0)

Above codes are 'Closed fracture of neck of femur'(concept id : 434500).

Please check the codes.

Thank you.

**Comment by chandryou** [comment]
Thank you for the comment.
I replaced the conditon_concept_id for # cases as you said. 

This will be reflected in KCD mapping table, too
